## Server Properties
server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    session:
      cookie:
        secure: true
        http-only: true

# Spring properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_network?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  # Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    check-location: true
    encoding: UTF-8
  # Mailing
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: testhw3@outlook.com
    password: mJ28UMXZ31kD
    properties.mail:
      protocol: smtp
      smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp-mail.outlook.com
    test-connection: true
  # JPA
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  #  session:
  #    jdbc:
  #      table-name: SPRING_SESSION
  #      initialize-schema: always
  #    store-type: jdbc
  devtools:
    restart:
      enabled: true
#  redis:
#    port: 6379

# Secure token configuration
gym-service:
  base-url-http: http://localhost:8080
  base-url-https: http://localhost:8080
  secure-token-validity: 28800
  jwt-secret: secret
  jwt-expiration-in-ms: 604800000

